<?php

const $ORGA_SERVER_NAME = "ORGA Server";
const $ORGA_SERVER_REALM = $ORGA_SERVER_NAME;

const $ORGA_SERVER_VERSION_MAJOR = 1;
const $ORGA_SERVER_VERSION_MINOR = 0;
const $ORGA_SERVER_VERSION_PATCH = 0;

const $ORGA_SERVER_VERSION =
    $ORGA_SERVER_VERSION_MAJOR.".".
    $ORGA_SERVER_VERSION_MINOR.".".
    $ORGA_SERVER_VERSION_PATCH;

const $ORGA_SERVER_NAME_FULL = "$ORGA_SERVER_NAME V$ORGA_SERVER_VERSION";

?>